- name: Docker related tasks
  hosts: localhost
  gather_facts: true
  remote_user: root
  connection: local
  tasks:
    - name: Debug
      become: true
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }} {{ ansible_facts }}"

