- name: Docker related tasks
  hosts: localhost
  gather_facts: true
  remote_user: root
  connection: local
  tasks:
    - name: Debug
      become: true
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"
    - name: Add docker repo
      become: true
      ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
      register: output
      changed_when: output.rc == 0
    - name: Install docker
      become: true
      ansible.builtin.command: dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
      register: output
      changed_when: output.rc == 0
    - name: Enable Docker service
      become: true
      ansible.builtin.systemd:
        name: docker
        enabled: true
    - name: Start Docker service
      become: true
      ansible.builtin.systemd:
        name: docker
        state: started
