- name: Post openstack deployment
  hosts: localhost
  remote_user: root
  connection: local
  tasks:
    - name: Install openstack client
      become: true
      ansible.builtin.command: pip install python-openstackclient -c https://releases.openstack.org/constraints/upper/2024.2
      register: output
      changed_when: output.rc == 0
    - name: Install manila client
      become: true
      ansible.builtin.command: pip install python-manilaclient -c https://releases.openstack.org/constraints/upper/2024.2
      register: output
      changed_when: output.rc == 0
    - name: Install magnum client
      become: true
      ansible.builtin.command: pip install python-magnumclient -c https://releases.openstack.org/constraints/upper/2024.2
      register: output
      changed_when: output.rc == 0
    - name: Post deployment auth generation
      become: true
      ansible.builtin.command: kolla-ansible post-deploy
      register: output
      changed_when: output.rc == 0
