- name: Post openstack deployment
  hosts: localhost
  remote_user: root
  connection: local
  tasks:
    - name: Install openstack.cloud collection
      ansible.builtin.command: ansible-galaxy collection install openstack.cloud
      register: output
      changed_when: output.rc == 0
    - name: Install openstack client
      become: true
      ansible.builtin.command: pip install python-openstackclient -c https://releases.openstack.org/constraints/upper/2024.2
      register: output
      changed_when: output.rc == 0
    - name: Install manila client
      become: true
      ansible.builtin.command: pip install python-manilaclient -c https://releases.openstack.org/constraints/upper/2024.2
      register: output
      changed_when: output.rc == 0
    - name: Install magnum client
      become: true
      ansible.builtin.command: pip install python-magnumclient -c https://releases.openstack.org/constraints/upper/2024.2
      register: output
      changed_when: output.rc == 0
    - name: Install octavia client
      become: true
      ansible.builtin.command: pip install python-octaviaclient -c https://releases.openstack.org/constraints/upper/2024.2
      register: output
      changed_when: output.rc == 0
    - name: Post deployment auth generation
      become: true
      ansible.builtin.command: kolla-ansible post-deploy
      register: output
      changed_when: output.rc == 0
    - name: Amphora image creation
      become: true
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          source /etc/kolla/octavia-openrc.sh
          openstack image create amphora-x64-haproxy.qcow2 \
          --container-format bare --disk-format qcow2 \
          --private \
          --tag amphora \
          --file /tmp/amphora-x64-haproxy.qcow2 \
          --property hw_architecture='x86_64' \
          --property hw_rng_model=virtio
      register: output
      changed_when: output.rc == 0
