apiVersion: v1
kind: Secret
metadata:
  name: harbor-creds-staging
  namespace: staging
type: kubernetes.io/docker-registry
stringData:
  docker-server: 172.10.1.159:30200
  docker-username: admin
  docker-password: Harbor12345