- name: Prepare VM Images
  hosts: localhost
  tasks:
    - name: Download Talos Linux
      ansible.builtin.get_url:
        url: https://factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/v1.11.5/openstack-amd64.raw.xz
        dest: /openstack-amd64.raw.xz
        mode: '0644'
    - name: Untar Talos Linux image file
      ansible.builtin.command: xz -d /openstack-amd64.raw.xz
      register: output
      changed_when: output.rc == 0
    - name: Create Talos Linux image
      openstack.cloud.image:
        state: present
        name: Talos Linux v1.11.5
        container_format: bare
        disk_format: raw
        filename: /openstack-amd64.raw
        properties:
          os_type: linux
          os_distro: talos
          os_version: 1.11.5
