apiVersion: v1
data:
  username: forgejo
  password: Zm9yZ2Vqbw==
kind: Secret
metadata:
  name: app-secret
type: kubernetes.io/basic-auth

---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-initdb
spec:
  instances: 3

  bootstrap:
    initdb:
      database: forgejo-db
      owner: forgejo
      secret:
        name: forgejo-secret

  storage:
    size: 10Gi