- name: Octavia setup
  vars_files: vars.yml
  hosts: localhost
  remote_user: root
  connection: local
  tasks:
    - name: Generate CA cert for Octavia deployment
      ansible.builtin.command: kolla-ansible octavia-certificates
      register: output
      changed_when: output.rc == 0
    - name: Octavia
      ansible.builtin.debug:
        msg: "octavia"

- name: Enable Octavia service
  ansible.builtin.import_playbook: setup-config-files.yml
