apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secret
data:
  username: Zm9yZ2Vqbw==
  password: Zm9yZ2Vqbw==
type: kubernetes.io/basic-auth

---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-db-cluster
spec:
  instances: 1

  bootstrap:
    initdb:
      database: forgejo-db
      owner: forgejo
      secret:
        name: forgejo-secret

  storage:
    size: 10Gi